$schema: "https://json-schema.org/draft/2020-12/schema"
description: global configuration
properties:
  manifest:
    type: string
  reference-fasta:
    type: string
  downsampled-variant-count:
    type: integer
    min: 5000
  dataset-name:
    type: string
required:
  - manifest
  - reference-fasta
  - downsampled-variant-count
  - dataset-name
additionalProperties: no
