$schema: "https://json-schema.org/draft/2020-12/schema"
description: tool/rule-specific resource configuration
properties:
  partitions:
    patternProperties:
      "^.*$":
        type: array
        items:
          type: string
  default: &defaults
    type: object
    properties:
      threads:
        type: integer
        min: 1
      memory:
        type: integer
        min: 100
      partition:
        type: string
    required:
      - threads
      - memory
      - partition
    additionalProperties: false
  bcftools-singlethreaded:
    <<: *defaults
  bcftools-multithreaded:
    <<: *defaults
  verifybamid2:
    <<: *defaults
required:
  - partitions
  - bcftools-singlethreaded
  - bcftools-multithreaded
  - verifybamid2
additionalProperties: false
